remote_theme: pages-themes/leap-day@v0.2.0

plugins:
- jekyll-remote-theme

title: Οἰκονομία
description: "Unless the Lord builds the house, those who build it labor in vain. (Psalm 127:1)"

show_downloads: false
